
import components.LocationPathBuilder
import kotlin.js.JsName
import kotlin.reflect.KProperty

/**
 * an xpath node test. more info [here](https://en.wikipedia.org/wiki/XPath#Node_tests)
 */
public open class NodeTest(public open val value: String) {
    override fun toString(): String = value
}

private class NodeTestDelegate {
    operator fun getValue(thisRef: Any?, property: KProperty<*>): NodeTest = NodeTest(property.name)
}

public class NodeTestFunction(public override val value: String) : NodeTest("$value()")

private class NodeTestFunctionDelegate {
    operator fun getValue(thisRef: Any?, property: KProperty<*>): () -> NodeTestFunction =
        { NodeTestFunction(property.name) }
}

//constants for HTML node tests (https://developer.mozilla.org/en-US/docs/Web/HTML/Element):
public val LocationPathBuilder.base: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.head: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.link: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.meta: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.style: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.title: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.body: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.address: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.article: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.aside: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.footer: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.header: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.h1: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.h2: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.h3: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.h4: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.h5: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.h6: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.hgroup: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.main: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.nav: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.section: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.blockquote: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.dd: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.div: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.dl: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.dt: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.figcaption: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.figure: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.hr: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.li: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.ol: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.p: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.ul: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.a: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.abbr: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.b: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.bdi: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.bdo: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.br: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.cite: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.code: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.data: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.dfn: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.em: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.i: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.kbd: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.mark: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.q: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.rb: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.rp: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.rt: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.rtc: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.ruby: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.s: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.samp: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.small: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.span: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.strong: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.sub: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.sup: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.time: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.u: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.`var`: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.wbr: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.area: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.audio: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.img: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.map: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.track: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.video: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.embed: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.iframe: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.`object`: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.param: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.picture: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.source: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.canvas: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.noscript: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.script: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.del: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.ins: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.caption: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.col: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.colgroup: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.table: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.tbody: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.td: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.tfoot: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.th: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.thead: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.tr: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.button: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.datalist: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.fieldset: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.form: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.input: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.label: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.legend: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.meter: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.optgroup: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.option: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.output: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.progress: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.select: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.textarea: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.details: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.dialog: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.menu: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.summary: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.slot: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.template: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.acronym: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.applet: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.basefont: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.bgsound: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.big: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.blink: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.center: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.command: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.content: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.dir: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.element: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.font: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.frame: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.frameset: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.image: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.isindex: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.keygen: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.listing: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.marquee: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.menuitem: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.multicol: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.nextid: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.nobr: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.noembed: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.noframes: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.plaintext: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.shadow: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.spacer: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.strike: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.tt: NodeTest by NodeTestDelegate()
public val LocationPathBuilder.xmp: NodeTest by NodeTestDelegate()

//node test functions
public val LocationPathBuilder.comment: () -> NodeTestFunction by NodeTestFunctionDelegate()
public val LocationPathBuilder.text: () -> NodeTestFunction by NodeTestFunctionDelegate()

@JsName("processing_instruction")
public fun LocationPathBuilder.`processing-instruction`(): NodeTestFunction = NodeTestFunction("processing-instruction")
public val LocationPathBuilder.node: () -> NodeTestFunction by NodeTestFunctionDelegate()