name: tests
on:
  push:
    branches:
      - master
    paths:
      - build.gradle.kts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gradle publish
        uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-14
    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_KEY: ${{ secrets.MAVEN_KEY }}