name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gradle tests
        uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-14
