name: tests
on:
  push: # every branch except master as thats handled by testAndDeploy
    branches-ignore:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gradle tests
        uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-14
