name: CI
on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gradle tests
        uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-14
